name: docker-compose-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*' # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Build the stack
        run: |
          sudo apt-get -y --no-install-recommends install \
          ca-certificates \
          build-essential \
          qemu-kvm \
          qemu-utils \
          curl \
          && apt-get clean \
          && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
          && curl https://ops.city/get.sh -sSfL | sh

      - run: |
          docker build -t my_mariadb_latest . && \
          $HOME/.ops/bin/ops pkg from-docker my_mariadb_latest -f my_mariadb_latest && \
          $HOME/.ops/bin/ops image create --package my_mariadb_latest -i my_mariadb_latest && \
          
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: "${{ github.ref_name }}.zip"
        
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ github.ref_name }}.zip"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
