name: docker-compose-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*' # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Build the stack
        run: |
          sudo apt-get -y --no-install-recommends install \
          ca-certificates \
          build-essential \
          qemu-kvm \
          qemu-utils \
          curl \
          && curl https://ops.city/get.sh -sSfL | sh

      - run: |
          docker build -t my_mariadb_latest . && \
          $HOME/.ops/bin/ops pkg from-docker my_mariadb_latest -c -n my_mariadb_latest -f mariadbd && \
          $HOME/.ops/bin/ops image list && \
          $HOME/.ops/bin/ops image create --package my_mariadb_latest -c config.json --imagename my_mariadb_latest --target-cloud onprem --local --nightly && \
          $HOME/.ops/bin/ops image list && \
          ls && \
          cd $HOME/.ops/images && \
          ls
          
          
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: "/home/runner/.ops/images/"
          filename: "${{ github.ref_name }}.zip"
        
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "/home/runner/.ops/images/${{ github.ref_name }}.zip"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
